In [43]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

In [29]:
# import train dataset
train = pd.read_csv('train.csv')
train.head()

,Unnamed: 0,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1,221900.0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,2,538000.0,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,3,180000.0,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,4,604000.0,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,5,510000.0,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [30]:
# import test dataset
test = pd.read_csv('test.csv')
test.head()

,Unnamed: 0,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,1001,3131200640,20150427T000000,700000.0,4,2.00,1830,4590,2.0,0,...,8,1830,0,1908,0,98105,47.6593,-122.327,1650,4590
1,1002,984000710,20141022T000000,270000.0,3,2.00,1560,8853,1.0,0,...,7,1560,0,1967,0,98058,47.4312,-122.171,1610,8750
2,1003,4167300350,20140508T000000,258000.0,4,1.75,1730,8320,1.0,0,...,7,1230,500,1977,0,98023,47.3270,-122.361,1840,9800
3,1004,2826049282,20140614T000000,530000.0,3,2.50,1930,7214,2.0,0,...,8,1930,0,2005,0,98125,47.7191,-122.309,1930,7266
4,1005,8946750030,20141218T000000,245000.0,3,2.25,1422,3677,2.0,0,...,7,1422,0,2012,0,98092,47.3204,-122.178,1677,3677

In [31]:
# TRAIN:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'zipcode', 'price']
x_train = train.drop(columns=columns_to_drop)
x_train.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,3,1.00,1180,5650,1.0,0,0,3,7,1180,0,1955,0,47.5112,-122.257,1340,5650
1,3,2.25,2570,7242,2.0,0,0,3,7,2170,400,1951,1991,47.7210,-122.319,1690,7639
2,2,1.00,770,10000,1.0,0,0,3,6,770,0,1933,0,47.7379,-122.233,2720,8062
3,4,3.00,1960,5000,1.0,0,0,5,7,1050,910,1965,0,47.5208,-122.393,1360,5000
4,3,2.00,1680,8080,1.0,0,0,3,8,1680,0,1987,0,47.6168,-122.045,1800,7503

In [32]:
# TEST:
# ignore columns: id, date and zipcode
# also ignore price column because this is the response and what we are trying to predict
columns_to_drop = ['Unnamed: 0', 'id', 'date', 'zipcode', 'price']
x_test = test.drop(columns=columns_to_drop)
x_test.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,lat,long,sqft_living15,sqft_lot15
0,4,2.00,1830,4590,2.0,0,0,3,8,1830,0,1908,0,47.6593,-122.327,1650,4590
1,3,2.00,1560,8853,1.0,0,0,3,7,1560,0,1967,0,47.4312,-122.171,1610,8750
2,4,1.75,1730,8320,1.0,0,0,3,7,1230,500,1977,0,47.3270,-122.361,1840,9800
3,3,2.50,1930,7214,2.0,0,0,3,8,1930,0,2005,0,47.7191,-122.309,1930,7266
4,3,2.25,1422,3677,2.0,0,0,3,7,1422,0,2012,0,47.3204,-122.178,1677,3677

In [33]:
# scale the data so that each feature has a mean of 0 and standard deviation of 1
scaler = StandardScaler()

# scale train dataset
for col in x_train:
    train_scaled = x_train[col].values.reshape(-1, 1) #reshape
    x_train[col] = scaler.fit_transform(train_scaled) 

# scale test dataset
for col in x_test:
    test_scaled = x_test[col].values.reshape(-1, 1) #reshape
    x_test[col] = scaler.fit_transform(test_scaled) 


# check mean and standard deviation of each feature to double check that scaling worked
for feature in x_train:
    mean = x_train.mean()
    std = x_train.var()

for feature in x_test:
    mean = x_test.mean()
    std = x_test.var()

# organize all variables into a table
stats_train = {
    'mean': mean,
    'std': std
}

stats_test = {
    'mean': mean,
    'std': std
}

feature_data_train = pd.DataFrame(stats_train)
feature_data_test = pd.DataFrame(stats_test)
feature_data_test

                       mean       std
bedrooms      -1.385558e-16  1.001001
bathrooms      2.122746e-16  1.001001
sqft_living   -2.113865e-16  1.001001
sqft_lot      -1.421085e-17  1.001001
floors        -8.704149e-17  1.001001
waterfront    -2.842171e-17  1.001001
view          -8.792966e-17  1.001001
condition      1.776357e-16  1.001001
grade         -3.215206e-16  1.001001
sqft_above     2.842171e-17  1.001001
sqft_basement  3.241851e-17  1.001001
yr_built      -2.083667e-15  1.001001
yr_renovated  -1.065814e-17  1.001001
lat            2.316725e-14  1.001001
long          -2.620659e-14  1.001001
sqft_living15 -7.283063e-17  1.001001
sqft_lot15     3.197442e-17  1.001001

In [9]:
# divide the price by 1000 for all rows in the train dataset
y_train = train['price'] / 1000
y_train

0      221.90
1      538.00
2      180.00
3      604.00
4      510.00
        ...
995    291.00
996    199.95
997    553.50
998    189.95
999    289.00
Name: price, Length: 1000, dtype: float64

In [34]:
# divide the price by 1000 for all rows in the test dataset
y_test = test['price'] / 1000
y_test

0      700.0
1      270.0
2      258.0
3      530.0
4      245.0
       ...
995    307.0
996    194.0
997    180.0
998    465.0
999    722.5
Name: price, Length: 1000, dtype: float64

In [35]:
# implement closed form solution:

# need to organize training data features into a matrix:
matrix_train = x_train.values
print(matrix_train)

price_matrix_train = y_train.values
print(price_matrix_train)

[[-0.40982347 -1.44988843 -0.98164572 ... -0.35519332 -0.96563661
  -0.3128578 ]
 [-0.40982347  0.28318404  0.58457767 ... -0.7998304  -0.44332966
  -0.23355563]
 [-1.58410276 -1.44988843 -1.44362529 ... -0.18307573  1.09374507
  -0.21669046]
 ...
 [-1.58410276 -1.44988843 -1.35348293 ... -0.86437449 -1.02532883
  -0.4185143 ]
 [-1.58410276 -1.44988843 -1.15066264 ...  1.07911986 -0.80148299
  -0.40352304]
 [-0.40982347 -0.06343045 -0.22670351 ... -0.46993837  0.39236146
  -0.15736334]]
[ 221.9    538.     180.     604.     510.    1225.     257.5    291.85
  229.5    323.     662.5    468.     310.     400.     530.     650.
  395.     485.     189.     230.     385.    2000.     285.     252.7
  329.     233.     937.     667.     438.     719.     580.5    280.
  687.5    535.     322.5    696.     550.     640.     240.     605.
  625.     775.     861.99   685.     309.     488.     210.49   785.
  450.    1350.     228.     345.     600.     585.     920.     885.
  292.5    301.     951.     430.     650.     289.     505.     549.
  425.     317.625  975.     287.     204.    1325.    1040.     325.
  571.     360.     349.     832.5    380.     480.     410.     720.
  390.     360.     355.     356.     315.     940.     305.     461.
  215.     335.     243.5   1099.88   153.     430.     700.     905.
  247.5    199.     314.     437.5    850.83   555.     699.95  1088.
  290.     375.     460.     188.5    680.     470.     597.75   570.
  272.5    329.95   480.     740.5    518.5    205.425  171.8    535.
  660.     391.5    395.     445.     770.    1450.     445.     260.
  822.5    430.     212.     660.5    784.     453.246  675.     199.
  220.     452.     382.5    519.95   665.     527.7    205.     420.
  500.     921.5    890.     430.     258.     511.     532.17   560.
  282.95  2250.     350.     215.     650.     320.     247.     320.
  255.     438.     900.     441.     420.     370.     269.95   807.1
  653.     371.5    284.     272.     313.     917.5    673.     425.
  399.95   385.     269.95   330.     260.     470.     589.     163.5
  835.    1095.     269.     560.     615.     585.188  305.     166.95
  799.     400.     230.     256.883  423.     465.     440.     385.
  210.     297.     470.     226.5    274.25   840.     677.9    425.
  180.25   464.     320.     625.504  592.5    465.     477.     280.
 1505.     445.838 1072.     467.     686.     279.95   527.     325.
  328.     390.     479.95   264.95   235.     516.5    655.     500.
  315.     213.     475.    1025.     416.     410.     800.     472.
  225.     210.     455.     225.     480.     363.    2400.     181.
  250.     481.     260.     455.     415.     349.5    245.     592.5
  385.     315.     255.     693.     780.     237.     525.     425.
  369.9    290.     285.     415.     272.5   2900.    1365.     436.
  210.     236.     331.     365.     450.     770.     455.     405.
  304.9    170.    2050.     780.     330.     370.     467.     405.
  675.     500.     389.999  630.     360.     580.     550.     879.
  265.     446.5    404.     267.5   3075.     335.     576.     208.633
  315.     725.     550.     610.75   550.7    665.     834.     201.
 2384.    1384.    1400.     305.     487.     390.     548.     268.75
  819.9    520.     230.     240.     232.     240.5    274.975  740.
  186.375  790.     880.     279.     295.     640.     940.     260.
  559.9    791.5    265.     245.     485.     684.     425.     309.6
  552.25   165.     239.9    320.     206.6    387.     299.     855.
  315.     437.5    252.     375.     300.     420.     900.     679.9
  463.     380.     329.5    604.95   795.     465.     673.     810.
  785.     338.     280.     315.     530.     380.     297.     730.
  450.     275.     595.     435.     270.     950.     389.     560.
 1350.     799.     365.5    252.35   403.95   385.     345.     490.
  330.     927.    1118.     330.     530.     365.     378.75   269.9
  557.     360.     352.     437.     322.5    650.     450.     278.5
  364.95   840.     268.     517.534  632.925  577.5    339.     570.
  563.5    423.     355.    1550.     482.     625.     538.     380.
  375.     245.     310.    1300.     397.     365.     328.5    988.
 1000.     237.     525.     749.     722.5    843.     438.     578.
  227.95   196.     641.     350.     205.     400.    1030.     505.
  475.     520.    1450.     333.5    232.     691.1    811.     551.
  496.5    705.     578.     255.    1050.     348.     230.     359.5
  330.      80.     465.     325.     340.5    342.5    290.9    868.7
 1199.    1150.     859.9    520.     460.     438.924  315.     590.
  378.5    328.5    849.95   525.    1385.     295.    1067.     207.95
  699.9   1280.     452.     370.     232.     669.95   397.5    490.
  725.     299.     625.     437.5    650.     475.     342.    1197.35
  280.     240.     529.     442.     615.    1485.     585.     480.
 1095.     290.     615.     300.     308.     750.    2250.     890.
  288.     190.     515.     235.     275.     727.5    650.    1600.
  365.     662.     270.5    200.     970.     160.     204.     358.
  452.     595.     249.     346.9   2125.     280.     318.888  530.
  375.     910.     782.     259.95   315.     215.     705.    1450.
  451.     261.     396.     725.    1950.     238.     750.     331.5
  460.     404.95   880.     863.     638.7    435.     260.     671.5
  610.     405.     338.9    720.     442.     650.     263.5    300.
  266.     930.     530.     180.     619.     264.     730.     439.
  268.5    330.     640.     900.     370.     685.     505.     265.
  290.     296.     360.     240.5    372.5    595.     515.    1220.
  507.     399.95   185.     460.     435.5    469.     531.     443.5
  223.     590.     340.     650.     533.6    695.     242.     425.
  525.     485.     175.     210.     260.     577.     200.     605.
  325.     289.5    559.95  1042.5    543.5    480.     218.     565.
  426.7    650.     542.     415.     214.     245.     314.5   1120.
  378.     305.     595.     729.5    430.     240.     545.     530.
  157.     425.     220.     521.     325.     597.5    337.    1000.
 3070.     495.     748.     888.     269.9    496.5    475.     312.
  323.     331.     306.     655.     290.    1250.     460.     435.
  664.     865.     385.     497.     280.     188.     478.5   1145.
  222.     799.     609.9    413.     400.     802.541  320.     507.
  387.5    396.     373.    1484.9    359.9    410.     690.     245.
  700.     268.     225.     980.     795.     195.     480.     485.
  130.     325.     440.     550.     310.     530.     390.     243.
  639.     215.     405.     250.     405.5    452.     730.     267.
  289.95   565.    1578.     636.     350.     320.     210.     245.
  328.     985.     501.     315.     403.     550.     347.5    365.
  588.     605.    1300.     233.     360.     459.     740.     305.
  395.     560.     650.     449.95   517.5    435.     329.999  950.
  447.     699.8    850.     316.5    942.5   1310.     856.6    405.6
  565.     400.     330.     374.95   405.3    560.     824.     260.
  760.     405.     429.9    341.5    465.25   450.     390.     420.
  269.95   493.     370.    2250.     305.     400.     320.     715.
  650.     218.     500.     460.     232.5    408.2    522.     675.
 1355.     249.95   210.     429.95   737.5    710.     470.    1100.
  650.    1216.     422.12   625.     385.2    500.     308.     565.
  581.     361.     345.     419.     347.     625.    2400.     379.
  310.     250.     682.     246.5    325.     310.95  1100.     287.5
  431.     226.     825.     175.     465.75   659.     595.     350.
  270.     662.5    249.9    324.5    430.     419.95   285.     332.
  282.     320.     428.75   330.     456.5    352.     664.     628.
  512.     254.     535.8    287.653  438.     450.     327.     370.5
  265.     450.     425.     166.6    245.     565.     539.9    910.
  280.     275.     467.     457.5    381.156  289.999  642.45   469.95
  795.     785.     860.    1095.     147.5    390.     229.     185.
  414.9    200.     225.     720.     930.    1270.     700.     466.
  374.     480.     740.    1010.     395.     340.     209.     431.65
  980.     660.     730.     291.5    905.     800.     839.9    200.
  300.     530.     314.95   255.     550.     435.     234.     615.
  205.     384.     324.     645.     570.     324.     270.     290.
  250.     342.     255.     800.     451.     990.     288.4    420.
  359.     390.     300.     545.     288.349  299.9    891.    1200.
  378.     299.995  253.     350.     565.     315.     570.     971.
  915.     419.     260.    1321.5    369.95  1029.9    435.     601.
  460.5    720.     851.     550.     700.     323.     345.5    378.
  650.     385.     425.     210.     630.     335.     196.5    582.8
  440.     752.5    532.5    265.     397.5    524.25   765.     648.
  469.5    237.5    216.     427.2    280.     718.     420.     379.
  326.1    535.     283.     260.     399.     484.95   640.     585.
  645.     253.     178.5    291.     199.95   553.5    189.95   289.   ]

In [38]:
# implement closed form solution:

# need to organize features into a matrix for test:
matrix_test = x_test.values
print(matrix_test)

price_matrix_test = y_test.values
print(price_matrix_test)

[[ 0.61971096 -0.12765819 -0.28513503 ... -0.83161535 -0.49282611
  -0.32497811]
 [-0.45245333 -0.12765819 -0.57291228 ...  0.32371455 -0.55042162
  -0.17705032]
 [ 0.61971096 -0.44286359 -0.39171919 ... -1.08341802 -0.21924741
  -0.13971278]
 ...
 [-0.45245333 -1.38847979 -1.15912519 ... -0.00955369 -1.34235996
  -0.12001278]
 [ 0.61971096  0.18754721  0.25844422 ...  1.31611331 -0.26244405
  -0.04256405]
 [ 0.61971096  0.50275261  0.38634522 ...  0.46442781  1.06225281
  -0.13615682]]
[ 700.     270.     258.     530.     245.     563.     515.     325.
  540.     280.3    460.     475.     900.     538.2    429.     164.808
  520.     475.     283.     321.5    840.     287.     375.     349.5
  446.45   315.     271.31   315.     245.     543.115  900.    2450.
  554.     249.9    768.     980.     395.     415.     380.     566.
  218.5    550.     512.031  197.5    470.     590.     465.     499.
  515.     716.5    410.     850.    1050.     648.     620.     935.
  379.     699.     528.     425.     249.5   1035.48   790.     399.95
  275.     550.     140.     250.     318.     505.     470.5    360.
 1242.5    986.     515.     320.     310.     356.7    775.     325.
  208.     825.     515.     490.     675.     360.     550.     225.
  500.     385.     837.7    448.     730.     575.     430.     435.
  241.     453.5    285.     151.    1570.     631.     285.     195.
  817.5    550.    1127.     609.85   200.     367.     285.167  275.
  350.9    660.     525.     262.     690.     624.     353.     552.5
  224.5    239.     975.    1200.     505.     302.     170.     195.
  272.     369.     332.5    515.     269.    1278.     303.     420.
  400.     225.     219.     605.     625.     380.     620.     687.5
  225.5    252.5    510.     510.     725.      75.     492.     425.
 1955.     298.9    699.     310.     350.     790.     305.     315.
  267.5   1750.     435.     482.5   5110.8    439.995  460.     194.
  290.     274.7    900.    1150.     605.     359.     850.     505.
  565.     585.     328.     749.95   826.     535.     925.     875.
  902.     423.     235.     545.     343.     334.95   405.     220.
  173.     655.     406.     632.     357.     361.     277.     630.
  254.     472.8    263.     510.     179.95   525.     479.     651.
  949.     392.4    585.     460.     470.     245.     500.     455.
  485.5   1875.     100.     307.     475.     330.     130.     320.
  735.     365.     234.     211.     680.     457.     349.     360.
  350.     208.     250.275  435.     270.     438.     659.     645.
  685.1    350.     375.     170.     880.     410.5    780.    1225.
  449.     546.     317.     276.9    399.     495.     258.     600.
  265.     321.     682.     295.7    609.     995.     530.     614.
  390.     467.     484.     340.     302.495  532.5    441.5    470.
 2300.     590.     320.     363.     747.5    750.     831.     403.
  445.     345.    2260.     371.025  355.     270.     425.     364.808
  320.     325.     350.     170.     255.     550.     835.     420.
  925.     389.25   748.     284.     588.     372.5    285.     360.
  275.     428.     847.     316.     375.     533.     556.     225.
  537.25   255.     530.    5300.     595.     548.     234.975  600.
  432.     455.     279.95   267.5    620.     110.     625.     389.
 1200.     788.5    567.     515.     605.     430.     805.     567.5
  647.5    495.     825.     435.     445.95   960.     780.     274.5
  729.953  464.95   620.     735.     450.     450.     842.5    360.
  585.     461.     345.    1075.     643.     690.     282.     549.
  815.    2200.     700.     933.399  290.     372.     450.     303.7
  672.     334.     260.     749.95   330.     830.    1131.     320.
  260.     225.     279.2    520.     505.     234.     503.     606.
  433.5    250.     719.     381.     267.     275.     651.     439.
  325.     490.     519.9    545.    1062.5    542.     465.     408.
  292.     253.     280.     658.588  635.     439.     300.     345.
  283.5    425.     685.     750.     245.     585.444  706.     445.
  241.    1175.     530.     350.    1700.     389.     799.    1400.
  340.895  780.     350.     470.     914.6    354.     470.     715.
  265.    2537.     640.     290.     480.     535.     907.     459.
 1355.     264.95   352.95   491.5   1229.     369.5    566.     290.
 5350.     180.     215.     302.     352.5    235.867  500.     382.
  515.     250.     672.5    755.     707.5    459.     140.     495.
  757.     765.     359.     440.     400.     652.     260.    1328.
  519.5    650.     280.     515.     400.     652.1    235.     701.
  640.     455.8    504.75   483.     530.     250.     229.95   884.744
  514.     532.     423.     420.     521.     577.     425.     495.
  340.     499.95  1218.     720.     249.     206.135  300.     612.
 1102.03   230.     850.     355.     442.     399.     360.     390.
  413.     190.     432.9    621.138  270.     610.     500.     715.
  264.     550.     337.     170.     405.     775.     425.     713.
  555.     810.    1250.     819.     409.9    935.     657.5    900.
  932.8    391.     420.    1300.     415.     350.     375.     860.
  495.     250.     365.     503.     150.     450.     355.     245.
  265.9    299.     957.5    343.     307.5    937.5    610.     720.
  610.     434.5    602.5    607.01   610.     828.5    199.99   294.
  789.5    797.     539.95   284.95   776.5    525.     303.     722.08
  140.     235.     440.     605.     380.     352.     420.    1175.
 1375.     300.    1150.     453.5    443.5    332.     655.     475.
  372.5   1050.     500.     900.     327.5    390.     451.101  455.
  650.     895.     800.     703.77   249.95   512.     780.     336.
  285.     229.9    667.5    378.     454.     537.5    425.     290.
  349.5    370.     549.5    245.     208.     248.     610.     550.
  750.     192.     169.317 1198.     880.     210.     180.5    540.
  520.     177.5    415.     495.     325.     440.     411.     810.
  561.75   835.1    450.     238.     299.     570.     340.     450.
  272.75   520.     284.95   255.     231.5    415.     330.     365.
  425.     400.     335.     342.     490.     331.5    960.     720.5
  830.     662.99   220.     349.95   550.     396.     635.     293.
  339.     285.     775.     224.    2250.     165.05   275.     445.
  510.    1230.     390.     460.     700.     874.15   470.     374.
  510.     467.     576.     196.44   825.     281.     326.     340.
  440.     749.     340.     561.     270.     600.     219.9    617.
  469.     229.    1265.     365.     429.     550.     453.     187.5
  520.5    300.     799.     338.     800.     360.     442.5    700.
  830.     360.4    345.     300.     350.     368.     264.     435.
  200.     620.    1679.     337.    1928.     544.5    252.     445.
  379.5    189.95   469.     600.     785.     372.     445.     508.
  780.     541.1    729.     397.     451.555  300.     416.     490.
  480.     368.    1038.     545.     850.     550.     600.     535.
  599.95   531.     530.     597.326  805.     390.     487.25   301.
 1175.     299.    2350.     400.     467.5    305.     210.     300.
  327.5    269.     975.     355.     712.     883.     190.     443.
  920.     285.     901.     552.5    256.     341.     279.     686.
  225.     215.5    950.     503.     780.     212.     580.     465.
  206.     615.     519.    1135.     330.     240.     574.     930.
  850.     415.     480.     300.     439.     450.     589.     477.
  587.5   1315.    1430.     700.     275.     367.5    453.25   607.
  255.     501.     450.     360.     460.     753.     389.95   469.
  550.     565.     189.65  1525.     260.     243.    1100.     249.
  720.     905.     824.5    762.5    580.     380.     805.     520.
 1569.5    175.     353.5    500.     386.5    210.     439.5    315.
  339.     655.     740.     685.     550.     405.     765.     625.
  207.     370.     475.     365.     411.8    668.     618.     247.5
  345.     616.3    348.     425.     850.     820.     832.     835.
  350.     349.    1125.     320.     150.     340.     785.5    410.5
  580.     345.     550.     449.5    300.     915.    1575.     599.
  755.     400.     133.     330.     330.     375.     485.     470.
 1045.     548.8    315.     590.     439.95   325.     400.     685.
  339.95   315.     411.753  577.     500.     210.     640.     460.
  265.     740.     230.     315.     432.     467.     255.     316.5
  190.     490.     378.     598.8    333.8    690.     320.    1249.
  335.     840.     608.25   550.     240.     998.     275.     284.2
 1715.    2400.     930.8    930.     215.     480.     483.945  347.
  232.5    390.     550.     590.     420.85   345.     429.8    302.
  800.     250.     605.     412.     252.     375.     725.     471.75
  490.     439.     355.     250.     780.     409.     420.     200.
  830.     695.     815.     210.     635.     562.5    402.5    555.
  310.     500.     430.    1600.     627.5    335.     962.     299.
  399.95   322.     430.     307.     194.     180.     465.     722.5  ]

In [49]:
# theta = ((x^T)*x)^-1 * (x^T)y

def closed_form_calc(matrix, price_matrix):

    x_t = matrix.T @ matrix

    x_t_inv = np.linalg.inv(x_t)

    x_t_y = matrix.T @ price_matrix

    theta = x_t_inv @ x_t_y

    return theta

theta_train = closed_form_calc(matrix_train, price_matrix_train)
theta_train

array([ -20.60779929,   24.6002802 , -117.55227383,   11.97226633,
          7.39278699,   64.21902716,   48.09557824,   13.1863707 ,
         91.16319067,  180.55046312,   70.53244241,  -67.64311741,
         17.27137953,   78.37573693,   -1.03520308,   45.57765781,
        -12.93009098])

In [45]:
# find MSE and r^2 value for train:

MSE_train = mean_squared_error(price_matrix_train, theta_train)
r2_train = r2_score(price_matrix_train, theta_train)

print('MSE metric: ', MSE_train)
print('R squared metric: ', r2_train)

ValueError: Found input variables with inconsistent numbers of samples: [1000, 17]

In [50]:
theta_test = closed_form_calc(matrix_test, price_matrix_test)
theta_test

array([ -53.00731021,   -2.41748907,  738.09572622,   28.29228042,
         -7.18303165,   74.43708466,   52.98815515,   22.15453383,
         92.71466834, -430.58318482, -278.07817508,  -72.50375394,
         -2.23381801,   77.61091444,  -10.3665892 ,   23.68905403,
        -23.85038144])